### ISSUE TITLE
How to make left stack view stick at the bottom.

### ISSUE THREAD

**Issue by moldovaniosif** [MessageKit/MessageInputBar#12]
Hi, I wanted to make the left stack view stick at the bootm of message input bar in the same way as "Send" button. Is this possible? 

![img_0033](https://user-images.githubusercontent.com/32193308/46650675-20cb3c80-cba6-11e8-8a27-afffbacd0d8d.PNG)

**Comment by nathantannar4** [comment]
Have you tried adjusting the alignment of the `InputStackView`?

**Comment by moldovaniosif** [comment]
Thank you @nathantannar4 for your replay, I tried the `InputStackView` bottom allignament but it didn't work. The implementation for `FacebookInputBar` from the Example app sheowed me the issue.
Actualy I mistakenly add as subview the attachment image view in the left stack view instead of calling:
`setStackViewItems([attachmentItem], forStack: .left, animated: false)`.
