### ISSUE TITLE
'MessageInputBarDelegate' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by himanthmaddi** [MessageKit/MessageInputBar#13]
In any class where I am confirming the MessageInputBarDelegate, it is giving me the error. How to solve this?

**Comment by nathantannar4** [comment]
Which version of MessageKit are you using?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
So it sounds like you are using MessageKit 1.0 and MessageInputBar? If you are also using MessageInputBar you have to update MessageKit to 2.0, currently we are on beta 1 for 2.0

**Comment by himanthmaddi** [comment]
Yeah I am using both MessageKit 1.0 and MessageInputBar. Is that making this problem?
