### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by fishcharlie** [MessageKit/MessageInputBar#15]
It looks like MessageKit has been updated to use Swift 4.2, but this library has not. Any ETA for when we can get complete Swift 4.2 support in MessageKit?

**Comment by nathantannar4** [comment]
This library is at Swift 4.2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fishcharlie** [comment]
<img width="264" alt="screen shot 2019-01-02 at 9 19 31 am" src="https://user-images.githubusercontent.com/860375/50600797-88281e00-0e6f-11e9-8569-77271999b576.png">

Are these errors known issues then? @nathantannar4

**Comment by nathantannar4** [comment]
Those errors show you build settings is set to Swift 4.2. It's stating that code in MessageInputBar uses Swift 4.2 so cannot be compiled with Swift 4

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fishcharlie** [comment]
@nathantannar4 Can't believe I missed that. For some reason I thought this project I'm working on was on Swift 4.2 instead of Swift 4. Changing it to Swift 4 works. Thanks!!
