### ISSUE TITLE
How to animate when add Bottom Stack View with bottomStackView.addArrangedSubview()

### ISSUE THREAD

**Issue by lalfuturedev** [MessageKit/MessageInputBar#18]

**Comment by lalfuturedev** [comment]
I just want to get animate both messageInputBar and collectionView in bottomStackViews from bottom to top.I tried with self.layoutIfNeeded() in UIView.animate function.It did animate but doesn't smooth.

**Comment by nathantannar4** [comment]
What method calls are you using? Please provide some code snippets else it's difficult for me to dubug what your doing. What's is happening and what do you expect to happen? "Doesn't smooth" isn't descriptive enough

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lalfuturedev** [comment]
Sorry for the unclear question.This is my code to animate bottomStackViews

`        let plusButton = InputBarButtonItem().onSelected {[weak self] (item) in
            guard let strongSelf = self else{
                return
            }
            
            if strongSelf.isBottomStackVisible{
                strongSelf.bottomStackView.removeArrangedSubview(strongSelf.bottomStackCollectionView)
            }else{
                strongSelf.bottomStackView.addArrangedSubview(strongSelf.bottomStackCollectionView)
            }
            
            UIView.animate(withDuration: 0.3, animations: {
                strongSelf.layoutIfNeeded()
            }, completion: { (_) in
                
            })
            
            strongSelf.isBottomStackVisible = !strongSelf.isBottomStackVisible
            item.image = strongSelf.isBottomStackVisible ? UIImage(named: "conv_cross_icon")!.withRenderingMode(.alwaysOriginal) : UIImage(named: "conv_plus_icon")!.withRenderingMode(.alwaysOriginal)
        }`

This is what I want to animate
![1 3jk-0e38mxxwv2a8sxbslg](https://user-images.githubusercontent.com/44859944/51094559-81d56280-17dc-11e9-88d7-40a2e3005137.gif)

**Comment by nathantannar4** [comment]
When you set the bottom stack view items don't make the call animated if you adding your own animation block. Also, call layoutIfNeeded on the collection view before the animation block so it's size(based on constraints) can be calculated

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lalfuturedev** [comment]
Thanks @nathantannar4 for giving your time...

**Comment by ducanh92hust** [comment]
What is the solution?
