### ISSUE TITLE
Images pasted into InputTextView have incorrect orientation

### ISSUE THREAD

**Issue by nfogg** [MessageKit/MessageInputBar#23]
I am having difficulty handling image orientations correctly in the InputTextView. Images attached from the Photos library or from the devices camera can appear sideways or upside down in the InputTextView. This is happening in MessageInputBar version 0.4.1.

  I am attaching images from a UIImagePickerController with the following code:
```swift
extension ConversationViewController: UIImagePickerControllerDelegate {
    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        if let image = info[UIImagePickerControllerOriginalImage] as? UIImage {
            messageInputBar.inputTextView.pasteImageInTextContainer(with: image)
            dismiss(animated: true, completion: nil)
        }
    }
}
```

  This problem can be reproduced using the ChatExample app in the simulator (iOS 12.1) with the following steps:
1. From the simulator's Photos app, copy the flowers photo to the clipboard
2. In the ChatExample app, paste the clipboard contents into the InputTextView

Note that the pasted image is upside down. 

<img width="200" alt="image" src="https://user-images.githubusercontent.com/29134991/53847861-63cef600-4006-11e9-89f9-8902bba310cd.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/29134991/53847923-a1cc1a00-4006-11e9-866f-a5e8547bccdb.png">

**Comment by nathantannar4** [comment]
Hmm, I just tried on my phone and it's the correct orientation. Could be a simulator issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 1640** [comment]
Change this
textAttachment.image = UIImage(cgImage: cgImage, scale: scale, orientation: .up) to textAttachment.image = UIImage(cgImage: cgImage, scale: scale, orientation: image.imageOrientation)

**Comment by nfogg** [comment]
Thanks @1640, your suggestion worked a treat!

@nathantannar4 I've created PR https://github.com/MessageKit/MessageInputBar/pull/25 with this small fix.

**Comment by nfogg** [comment]
Closing now that PR #25 has been merged.
