### ISSUE TITLE
Swipe to hide keyboard on IphoneXS Max

### ISSUE THREAD

**Issue by hhoangna** [MessageKit/MessageInputBar#26]
On iphone XS Max i found this bug. I already tested on your source code and found same bug. Please fix!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26923574/58146400-1dda1380-7c80-11e9-9266-cef0fc5acc2c.gif)

**Comment by nathantannar4** [comment]
What's the bug? I don't see the issue from your Gif. What's your expected result?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
