### ISSUE TITLE
Value of type 'InputItem' has no member 'isEnabled'

### ISSUE THREAD

**Issue by hechukwu** [MessageKit/MessageInputBar#28]
I want to disable the leftStackViewItem when sending a photo, so I do this `self.messageInputBar.leftStackViewItems.forEach { item in
                    item.isEnabled = !self.isSendingPhoto
                }` but I get this error `Value of type 'InputItem' has no member 'isEnabled'`

**Comment by isupremedyou** [comment]
`InputBarButtonItem` is a subclass of `UIButton` and conforms to the protocol `InputItem`. So long as your left stack view items are all `InputBarButtonItem` then you can try casting them: `as? InputBarButtonItem` and that should resolve your error.

**Comment by hechukwu** [comment]
Thank you @travischapman for your help, you saved me days of debugging.

**Comment by emmismtv** [comment]
So what would be the final code? Still new is this kind of things.

**Comment by hechukwu** [comment]
self.messageInputBar.leftStackViewItems.forEach { item in
                    guard let item = item as? InputBarButtonItem else { return }
                    item.isEnabled = !self.isSendingPhoto
                }

**Comment by emmismtv** [comment]
Thanks!
